### ISSUE TITLE
Running `speech_recognition.py`

### ISSUE THREAD

**Issue by LysandreJik** [kennylajara/speech-recognition#1]
Hi. I believe you're opening an issue because of two problems, first this warning:
```
/home/xxx/Workspaces/Python/speech-recognition/.env/lib/python3.9/site-packages/transformers/models/wav2vec2/tokenization_wav2vec2.py:417: FutureWarning: The class `Wav2Vec2Tokenizer` is deprecated and will be removed in version 5 of Transformers. Please use `Wav2Vec2Processor` or `Wav2Vec2CTCTokenizer` instead.
```
Is there something wrong with the warning? It tells you that `Wav2Vec2Tokenizer` is deprecated and you should use `Wav2Vec2CTCTokenizer`.

Secondly, my console doesn't get closed, I get the following output:
```
['mi ojeto favorito yo creo que e mi ordenador porque lo huso tanto para trabajar como para entretenerme para trabajar o para estudiar e cosa de la universidad e incluso para ver película e creo que e de lo má útil que tengo y á la ve de lo más entretenido']
```

**Comment by kennylajara** [comment]
Thank you but if I use `Wav2Vec2CTCTokenizer` I get this error:

```
Traceback (most recent call last):
  File "/home/user/dev/speech_recognition.py", line 19, in <module>
    input_values = tokenizer(waveform, return_tensors='pt').input_values
  File "/home/user/dev/venv/lib64/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2284, in __call__
    raise ValueError(
ValueError: text input must of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).
```
